# :: SERVICE ::
# Key passed as query param to access endpoints
AUTH_KEY: "shorty"
# The base url used by short urls to produce full url
BASE_URL: "http://localhost:8080"
# Minimum size of hash code for short url
HASH_MIN: 5
# Seed used to start url hash (unique make it less predicable)
HASH_SALT: "$h0rtur1$"
# Server name and port
SERVER_ADDR: ":8080"
# Store to use - badger|mongo
STORE: "badger"


# :: MONGO DB ::
# MongoDb address
MONGO_URL: "mongodb://localhost:27017"
# Name of the mongo database
MONGO_DB: "shorturls"
# [!] Mongo caches queries to reduce calls to database
# Number of minutes the short url request is kept in memory (mongo only)
MONGO_CACHE_EXP: 15
# Number of minutes cleanup should remove expired urls (mongo only)
MONGO_CACHE_CLEANUP: 60
# [!] Mongo uses two collections
MONGO_COL_COUNTER: "counter"
MONGO_COL_LINKS: "links"


# :: BADGER ::
# Path to store Badger database
BADGER_DIR: "./data/badger"