version: '3.3'
services:

  app:
    image: "roboncode/shorturls"
    tty: false
    restart: always
    ports:
      - 1323:1323
    depends_on:
      - db

  db:
    image: mongo
    container_name: "mongo_shorturls"
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db

